name: Dependabot auto-merge
on: pull_request

jobs:
  automerge:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
      - name: Approve a PR
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        if: steps.metadata.outputs.version-update != 'version-update:semver-major'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
